[build]
  command = "pip install pipenv && pipenv install --deploy --system && pip install sqlalchemy-serializer"
  publish = "public"

[dev]
  command = "pipenv run python server/app.py"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.8"

[functions]
  directory = "server"

[[plugins]]
package = "@netlify/plugin-functions-install-core"