[build]
  command = "pip install pipenv && pipenv install --deploy --system && pip install sqlalchemy-serializer && python server/app.py"
  publish = "public"

[dev]
  command = "pipenv run python server/app.py"  # Command to start your dev server

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.8"  # Specify the Python version you're using
