[build]
  command = "pip install pipenv && pipenv install --deploy && pipenv run python server/app.py"
  publish = "public"  # Adjust this if your publish directory is different

[dev]
  command = "pipenv run python server/app.py"  # Command to start your dev server

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.8"  # Specify the Python version you're using
