[build]
  command = "pip install pipenv && pipenv install --deploy --system && pip install sqlalchemy-serializer"
  functions = "server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/netlify"
  status = 200

[functions]
  directory = "server"