[build]
  command = "pip install pipenv && pipenv install --deploy --system && pip install sqlalchemy-serializer"

[build.environment]
  PYTHON_VERSION = "3.8"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "server"